---
app_dir: "/srv/AppData"
app_user: "k0ng"
airsonic_dir: "{{ app_dir }}/airsonic"
compose_dir: "{{ app_dir }}/compose"
df_compose_dir: "{{ app_dir }}/dragonfly/deploy/docker-compose"
domain: "superasian.net"
dragonfly_dir: "{{ app_dir }}/dragonfly"
grafana_dir: "{{ app_dir }}/grafana"
influxdb_dir: "{{ app_dir }}/influxdb"
nginx_dir: "{{ app_dir }}/nginx"
portainer_dir: "{{ app_dir }}/portainer"
repo_url: "https://www.superasian.net/repo"
srv_ip: "10.0.0.19"
telegraf_dir: "{{ app_dir }}/telegraf"
vault_dir: "{{ app_dir }}/vault"
