---
app_dir: "/srv/AppData"
app_user: "k0ng"
airsonic_dir: "{{ app_dir }}/airsonic"
compose_dir: "{{ app_dir }}/compose"
domain: "superasian.net"
mon_dir: "{{ app_dir }}/monitoring"
nginx_dir: "{{ app_dir }}/nginx"
portainer_dir: "{{ app_dir }}/portainer"
grafana_dir: "{{ mon_dir }}/grafana"
influxdb_dir: "{{ mon_dir }}/influxdb"
prometheus_dir: "{{ mon_dir }}/prometheus"
telegraf_dir: "{{ mon_dir }}/telegraf"
repo_url: "https://www.superasian.net/repo"
srv_ip: "10.0.0.25"
vault_dir: "{{ app_dir }}/vault"
