---
app_dir: "/srv/AppData"
app_user: "k0ng"
compose_dir: "{{ app_dir }}/compose"
df_compose_dir: "{{ app_dir }}/dragonfly/deploy/docker-compose"
dragonfly_dir: "{{ app_dir }}/dragonfly"
grafana_dir: "{{ app_dir }}/grafana"
influxdb_dir: "{{ app_dir }}/influxdb"
nginx_dir: "{{ app_dir }}/nginx"
telegraf_dir: "{{ app_dir }}/telegraf"
vault_dir: "{{ app_dir }}/vault"
domain: "superasian.net"
srv_ip: "10.0.0.19"
