---
app_dir: "/srv/AppData"
app_user: "k0ng"
airsonic_dir: "{{ app_dir }}/airsonic"
compose_dir: "{{ app_dir }}/compose"
domain: "superasian.net"
nginx_dir: "{{ app_dir }}/nginx"
portainer_dir: "{{ app_dir }}/portainer"
pm_dir: "{{ app_dir }}/monitoring"
grafana_dir: "{{ pm_dir }}/grafana"
prometheus_dir: "{{ pm_dir }}/prometheus"
repo_url: "https://www.superasian.net/repo"
srv_ip: "10.0.0.25"
vault_dir: "{{ app_dir }}/vault"
