---
app_dir: "/AppData"
app_user: "k0ng"
artifactory_user: "1030"
artifactory_group: "1030"
artifactory_version: "7.111.8"
jfrog_product: "artifactory-jcr"
srv_ip: "10.0.0.18"
db_ip: "10.0.0.252"
db_port: "5432"
