---
app_dir: "/AppData"
app_user: "k0ng"
artifactory_user: "1030"
artifactory_group: "1030"
version: "7.117.17"
jfrog_product: "jfrog-artifactory-oss"
jfrog_product_base_url: "https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/docker/jfrog-artifactory-oss"
srv_ip: "10.0.0.18"
