---
app_dir: "/AppData"
app_user: "k0ng"
artifactory_user: "1030"
artifactory_group: "1030"
version: "7.111.8"
product: "artifactory-jcr"
srv_ip: "10.0.0.18"
jcr_url: "https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/jcr/jfrog-artifactory-jcr"
