---
app_dir: "/srv/AppData"
app_user: "k0ng"
artifactory_user: "1030"
artifactory_group: "1030"
version: "7.125.12"
product: "artifactory-oss"
srv_ip: "10.0.0.25"
repo_url: "https://www.superasian.net/repo"
#jcr_url: "https://releases.jfrog.io/{{ version }}/jfrog-{{ product }}-{{ version}}-compose.tar.gz"
#curl -g -L -O -J 'https://releases.jfrog.io/{{ version }}/{{ product }}-{{ version}}-compose.tar.gz'
