---
app_dir: "/srv/AppData"
app_user: "k0ng"
artifactory_user: "1030"
artifactory_group: "1030"
version: "7.125.11"
product: "artifactory-oss"
srv_ip: "10.0.0.25"
jcr_url: "https://www.superasian.net/repo"
