#SPDX-License-Identifier: MIT-0
---
app_dir: "/srv/AppData"
app_user: "k0ng"
compose_dir: "{{ app_dir }}/compose"
domain: "superasian.net"
mon_dir: "{{ app_dir }}/monitoring"
grafana_dir: "{{ mon_dir }}/grafana"
influxdb_dir: "{{ mon_dir }}/influxdb"
prometheus_dir: "{{ mon_dir }}/prometheus"
telegraf_dir: "{{ mon_dir }}/telegraf"
repo_url: "https://www.superasian.net/repo"
srv_ip: "10.0.0.25"
