---
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Deploy apps-dir
  ansible.builtin.include_tasks: apps-dir.yml

- name: Setup nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Deploy airsonic
  ansible.builtin.include_tasks: airsonic.yml

- name: Setup monitoring
  ansible.builtin.include_tasks: monitoring.yml

- name: Setup vault
  ansible.builtin.include_tasks: vault.yml
  