---
- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Deploy apps-dir
  ansible.builtin.include_tasks: apps-dir.yml

- name: Deploy airsonic
  ansible.builtin.include_tasks: airsonic.yml

- name: Setup dragonfly
  ansible.builtin.include_tasks: dragonfly.yml

- name: Setup grafana
  ansible.builtin.include_tasks: grafana.yml

- name: Setup influxdb
  ansible.builtin.include_tasks: influxdb.yml

- name: Setup nginx
  ansible.builtin.include_tasks: nginx.yml

- name: Setup portainer
  ansible.builtin.include_tasks: portainer.yml

- name: Setup telegraf
  ansible.builtin.include_tasks: telegraf.yml

- name: Setup vault
  ansible.builtin.include_tasks: vault.yml
  