DOCKER_REGISTRY: {}
ARTIFACTORY_VERSION: {}
ROOT_DATA_DIR: {}
JF_ROUTER_ENTRYPOINTS_EXTERNALPORT: {}
JF_ROUTER_ENTRYPOINTS_INTERNALPORT: {}
JF_SHARED_NODE_IP: {}
JF_SHARED_NODE_ID: {}
JF_SHARED_NODE_NAME: {}