DOCKER_REGISTRY: "releases-docker.jfrog.io"
ARTIFACTORY_VERSION: 7.125.11
ROOT_DATA_DIR: "/srv/AppData/artifactory"
JF_ROUTER_ENTRYPOINTS_EXTERNALPORT: 8082
JF_ROUTER_ENTRYPOINTS_INTERNALPORT: {}
JF_SHARED_NODE_IP: 10.0.0.25
JF_SHARED_NODE_ID: 10.0.0.25
JF_SHARED_NODE_NAME: artifactory-oss