---
app_dir: "/srv/AppData"
app_user: "k0ng"
df_dir: "{{ app_dir }}/dragonfly"
nginx_dir: "{{ app_dir }}/nginx"
srv_ip: "10.0.0.25"
version: "2.4.1"
df_pkg: "https://github.com/dragonflyoss/dragonfly/releases/download/v{{ version }}/dragonfly-{{ version }}-linux-amd64.tar.gz"