---
app_dir: "/srv/AppData"
app_user: "k0ng"
df_compose_dir: "{{ app_dir }}/dragonfly/deploy/docker-compose"
dragonfly_dir: "{{ app_dir }}/dragonfly"
nginx_dir: "{{ app_dir }}/nginx"
srv_ip: "10.0.0.25"
