---
app_dir: "/srv/AppData"
domain: "registry.superasian.net"
app_user: "k0ng"
nginx_dir: "{{ app_dir }}/nginx"
registry_dir: "{{ app_dir }}/registry"
registry_ui_dir: "{{ registry_dir }}/ui"
srv_ip: "10.0.0.25"
