app_dir: "/srv/AppData"
app_user: "k0ng"
domain: "harbor.superasian.net"
github_url: "https://github.com/goharbor/harbor/releases/download"
harbor_version: "v2.14.0"
harbor_dir: "{{ app_dir }}/harbor"