---
name: Uptime-Kuma
services:
  app:
    image: louislam/uptime-kuma:nightly2-rootless
    container_name: uptime-kuma
    volumes:
      - /srv/AppData/uptime-kuma:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    network_mode: bridge

volumes:
  data:
    driver: local