shared:
    node:
        ip: 10.0.0.25
        id: n4s-i5-2400
        name: n4s-i5-2400
    database:
        type: postgresql
        driver: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/artifactory
        username: artifactory
        password: P@ssw0rd
router:
    entrypoints:
        externalPort: 8082
observability:
    consumption:
        allow: ""