shared:
    node:
        ip: {{ srv_ip }}
        id: n4s-i5-2400
        name: n4s-i5-2400
    database:
        type: postgresql
        driver: org.postgresql.Driver
        url: jdbc:postgresql://10.0.0.252:5432/artifactory
        username: artifactory
        password: P@ssw0rd
router:
    entrypoints:
        externalPort: 8082
observability:
    consumption:
        allow: ""