#SPDX-License-Identifier: MIT-0
---
- name: Restart docker
  ansible.builtin.service:
    state: restarted
    name: docker

- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl

- name: Restart firewalld
  ansible.builtin.service:
    state: restarted
    name: firewalld

- name: Restart nginx
  ansible.builtin.command: |
    docker restart nginx
  async: 1
  poll: 0

- name: Reboot host
  ansible.builtin.reboot:
    reboot_timeout: 300
